# Generated by Django 2.1.1 on 2018-10-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20181002_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('endereco', models.CharField(max_length=200)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.OneToOneField(blank=True, null=True, on_delete=0, to='clientes.CPF')),
                ('departamentos', models.ManyToManyField(blank=True, to='clientes.Departamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='clientes',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='telefone',
            name='empregado',
            field=models.ForeignKey(default=1, on_delete=0, to='clientes.Empregado'),
            preserve_default=False,
        ),
    ]
